# Generated by Django 5.2.4 on 2025-08-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(default='FOLIO', max_length=20, unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
