# Generated by Django 5.2.4 on 2025-08-11 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0002_consecutivofolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='tema',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
