# Generated by Django 5.2.4 on 2025-08-12 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0003_alter_tema_options_tema_activo_tema_creado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='folio',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='folios.tema'),
        ),
    ]
