# Generated by Django 5.2.4 on 2025-08-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0005_seed_consecutivo_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consecutivofolio',
            name='llave',
            field=models.CharField(default='FOLIO', max_length=30, unique=True),
        ),
    ]
