# Generated by Django 5.2.4 on 2025-08-17 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0006_alter_consecutivofolio_llave'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='concluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios_concluidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folio',
            name='fecha_conclusion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
